INSERT INTO Genres (GenreType) VALUES ('Action');
INSERT INTO Genres (GenreType) VALUES ('Adventure');
INSERT INTO Genres (GenreType) VALUES ('Comedy');
INSERT INTO Genres (GenreType) VALUES ('Crime');
INSERT INTO Genres (GenreType) VALUES ('Drama');
INSERT INTO Genres (GenreType) VALUES ('Fantasy');
INSERT INTO Genres (GenreType) VALUES ('Historical');
INSERT INTO Genres (GenreType) VALUES ('Historical Fiction');
INSERT INTO Genres (GenreType) VALUES ('Horror');
INSERT INTO Genres (GenreType) VALUES ('Magical Realism');
INSERT INTO Genres (GenreType) VALUES ('Mystery');
INSERT INTO Genres (GenreType) VALUES ('Philosophical');
INSERT INTO Genres (GenreType) VALUES ('Political');
INSERT INTO Genres (GenreType) VALUES ('Romance');
INSERT INTO Genres (GenreType) VALUES ('Saga');
INSERT INTO Genres (GenreType) VALUES ('Satire');
INSERT INTO Genres (GenreType) VALUES ('Science Fiction');
INSERT INTO Genres (GenreType) VALUES ('Thriller');
INSERT INTO Genres (GenreType) VALUES ('Western');
INSERT INTO Genres (GenreType) VALUES ('Bakunyū');
INSERT INTO Genres (GenreType) VALUES ('Bara');
INSERT INTO Genres (GenreType) VALUES ('Boys''Love');
INSERT INTO Genres (GenreType) VALUES ('Gei comi');
INSERT INTO Genres (GenreType) VALUES ('Harem');
INSERT INTO Genres (GenreType) VALUES ('Isekai');
INSERT INTO Genres (GenreType) VALUES ('Lolicon');
INSERT INTO Genres (GenreType) VALUES ('Mecha');
INSERT INTO Genres (GenreType) VALUES ('Shōjo-ai');
INSERT INTO Genres (GenreType) VALUES ('Shōnen-ai');
INSERT INTO Genres (GenreType) VALUES ('Shotacon');
INSERT INTO Genres (GenreType) VALUES ('Yaoi');
INSERT INTO Genres (GenreType) VALUES ('Yuri');
INSERT INTO Genres (GenreType) VALUES ('Cyberpunk');