insert into series (Title,CreatorAuthorId) values ('Akira',1);
insert into series (Title,CreatorAuthorId) values ('Blood:The Last Vampire',2);
insert into series (Title,CreatorAuthorId) values ('Blue Submarine No. 6',3);
insert into series (Title,CreatorAuthorId) values ('Bubblegun Crisis',4);
insert into series (Title,CreatorAuthorId) values ('Bubblegun Crisis Tokyo 2040',5);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Card Capture Sakura',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Cowboy Bebop',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Dual',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('El Hazard',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Gasaraki',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Ghost in the Shell',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Grave of Fireflies',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Iria',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Martian Successor Nadesico',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Mobile Suit Gundam 0080: War in the Pocket',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Mobile Suit Gundam: 0083 Stardust Memory',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Mononoke Hime',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Neon Genesis Evangelion',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Ninja Resurrection',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Ninja Scroll',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Ranma 1/2',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Record of Lodoss Wars',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Record of Lodoss Wars TV',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Robotech',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Rurouni Kenshin',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Rurouni Kenshin/Samurai X',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Sakura Tsushin/Sakura Diaries',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Tenchi Muyo!',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('The Vision of Escaflowne',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Trigun',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('Wicked City',);
--insert into series (Title,CreatorAuthorId,GenreId) values ('X',);
