INSERT INTO Series (Title) VALUES ('Akira');
INSERT INTO Series (Title) VALUES ('Blood:The Last Vampire');
INSERT INTO Series (Title) VALUES ('Blue Submarine No. 6');
INSERT INTO Series (Title) VALUES ('Bubblegun Crisis');
INSERT INTO Series (Title) VALUES ('Bubblegun Crisis Tokyo 2040');
INSERT INTO Series (Title) VALUES ('Card Capture Sakura');
INSERT INTO Series (Title) VALUES ('Cowboy Bebop');
INSERT INTO Series (Title) VALUES ('Dual! Parallel Trouble Adventure');
INSERT INTO Series (Title) VALUES ('El Hazard');
INSERT INTO Series (Title) VALUES ('Gasaraki');
INSERT INTO Series (Title) VALUES ('Ghost in the Shell');
INSERT INTO Series (Title) VALUES ('Grave of Fireflies');
INSERT INTO Series (Title) VALUES ('Iria: Zeiram the Animation'); -- Three writers
INSERT INTO Series (Title) VALUES ('Martian Successor Nadesico');
INSERT INTO Series (Title) VALUES ('Mobile Suit Gundam 0080: War in the Pocket');
INSERT INTO Series (Title) VALUES ('Mobile Suit Gundam: 0083 Stardust Memory');
INSERT INTO Series (Title) VALUES ('Mononoke Hime');
INSERT INTO Series (Title) VALUES ('Neon Genesis Evangelion');
INSERT INTO Series (Title) VALUES ('Ninja Resurrection');
INSERT INTO Series (Title) VALUES ('Ninja Scroll');
INSERT INTO Series (Title) VALUES ('Ranma 1/2');
INSERT INTO Series (Title) VALUES ('Record of Lodoss Wars');
INSERT INTO Series (Title) VALUES ('Record of Lodoss Wars TV');
INSERT INTO Series (Title) VALUES ('Rurouni Kenshin');
INSERT INTO Series (Title) VALUES ('Rurouni Kenshin/Samurai X');
INSERT INTO Series (Title) VALUES ('Sakura Tsushin/Sakura Diaries');
INSERT INTO Series (Title) VALUES ('Tenchi Muyo!');
INSERT INTO Series (Title) VALUES ('The Vision of Escaflowne');
INSERT INTO Series (Title) VALUES ('Trigun');
INSERT INTO Series (Title) VALUES ('Wicked City');
INSERT INTO Series (Title) VALUES ('X');
