INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Katsuhiro','Otomo')
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Mamoru','Oshii')
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Satoru','Ozawa')
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Toshimichi','Suzuki')
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Chiaki','Konaka')
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Clamp','');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Keiko','Nobumoto');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Yōsuke','Kuroda');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Ryoe','Tsukimura');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Ryousuke','Takahashi');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Hajime','Yatate');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Masamune','Shirow');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Akiyuki','Nosaka');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Shō','Aikawa');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Hayao','Miyazaki');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Hideaki','Anno');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Futaro','Yamada');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Yoshiaki','Kawajiri');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Rumiko','Takahashi');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Ryo','Mizuno');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Nobuhiro','Watsuki');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Kenji','Terada');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Masaki','Kajishima');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Hiroki','Hayashi');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Shōji','Kawamori');
INSERT INTO CreatorAuthors (FirstName,LastName) VALUES ('Yasuhiro','Nightow');