INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('A-1 Pictures');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('A.P.P.P.');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Anime International Company|AIC');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Arms Corporation');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Artland (company)|Artland');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Asahi Production');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Asread');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Bee Train');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Bones (studio)|Bones');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Brain''s Base');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('C2C (studio)|C2C');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('CoMix Wave Films');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Daume');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('David Production');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Doga Kobo');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('DLE (company)|DLE');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Dwarf Studios');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Egg Firm');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Eiken (studio)|Eiken');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Gainax');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Gallop (studio)|Gallop');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Gonzo (company)|Gonzo');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Group TAC');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Hal Film Maker');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Imagin (studio)|Imagin');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('J.C.Staff');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Japan Vistec');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Khara (studio)|Khara');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Kitty Films');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Kyoto Animation');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Lerche (studio)|Lerche');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Madhouse (company)|Madhouse');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Magic Bus (studio)|Magic Bus');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Mook Animation');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Mushi Production');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Nippon Animation');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Nomad (company)|Nomad');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('OLM, Inc.|OLM');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Ordet (studio)|Ordet');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('P.A.Works');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Pierrot (company)|Pierrot');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Polygon Pictures');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Production I.G');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Radix Ace Entertainment');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Satelight');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Seven Arcs');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Shaft (company)|Shaft');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Studio 4°C');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Studio Comet');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Studio Deen');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Studio Donguri');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Studio Dub');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Studio Egg');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Studio Fantasia');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Studio Ghibli');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Studio Hibari');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Studio Junio');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Studio Nue');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Studio Orphee');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Studio Wombat');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Sunrise (company)|Sunrise');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('SynergySP');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Tatsunoko Production');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Telecom Animation Film');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Tezuka Productions');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('TMS Entertainment');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('TNK (company)|TNK');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Toei Animation');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Topcraft');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Triangle Staff');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Trigger (company)|Trigger');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Ufotable');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('White Fox');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Wit Studio');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Xebec (studio)|Xebec');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Yumeta Company');
INSERT INTO ProductionStudios (ProductionStudioName) VALUES ('Zexcs');
