BEGIN TRANSACTION;


INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('A-1 Pictures','Japan','https://a1p.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('A.P.P.P.','Japan','http://appp.web.fc2.com/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Anime International Company | AIC','Japan','http://www.anime-int.com/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Arms Corporation','Japan','http://www.a-rms.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Artland Inc.','Japan','http://www.artland.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Asahi Production','Japan','http://www.asahi-pro.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Asread','Japan','http://www.asread.net/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Bee Train Production','Japan','http://www.beetrain.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Bones','Japan','http://www.bones.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Brain''s Base','Japan','http://www.brainsbase.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('C2C','Japan','http://www.c2c2009.com/en');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('CoMix Wave Films','Japan','http://www.cwfilms.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Daume','Japan','http://daume.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('David Production','Japan','http://davidproduction.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Doga Kobo','Japan','http://www.dogakobo.com/en');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Dream Link Entertainment | DLE','Japan','http://www.dle.jp/en/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Dwarf Studios','Japan','http://www.dw-f.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('EGG FIRM','Japan','http://www.eggfirm.com/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Eiken','Japan','http://www.eiken-anime.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Gainax','Japan','http://www.gainax.co.jp/wp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Gallop Co., Ltd | Studio Gallop','Japan','http://www.anime-gallop.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Gonzo K.K. | Gonzo','Japan','http://www.gonzo.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Group TAC','Japan','http://web.archive.org/web/20070223083159/http://www.g-tac.co.jp/home.html');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Hal Film Maker','Japan','http://web.archive.org/web/20070303152046/http://www.hal-film.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Imagin Co., Ltd. | Imagin','Japan','http://www.imagin-do.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('J.C.Staff','Japan','http://www.jcstaff.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Japan Vistec','Japan','http://www.jvi.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Khara, Inc. | Khara','Japan','http://www.khara.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Kitty Films','Japan','http://www.kitty.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Kyoto Animation','Japan','http://www.kyotoanimation.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Lerche | Studio Hibari','Japan','http://www.lerche.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Madhouse Inc. | Madhouse','Japan','http://www.madhouse.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Magic Bus','Japan','http://magicbus.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Mook Animation','Japan','http://mookanimation.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Mushi Production','Japan','http://www.mushi-pro.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Nippon Animation','Japan','http://www.nippon-animation.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Nomad Inc. | Nomad','Japan','http://www.nomad-inc.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('OLM, Inc. | OLM','Japan','https://www.olm.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Ordet Co., Ltd. | Ordet','Japan','http://uspi.jp/ordet/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('P.A.Works','Japan','http://www.pa-works.jp/en/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Pierrot Co., Ltd. | Pierrot','Japan','http://en.pierrot.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Polygon Pictures','Japan','http://www.ppi.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Production I.G','Japan','http://www.production-ig.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Radix Ace Entertainment','Japan','http://www.radixzero.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Satelight','Japan','http://www.satelight.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Seven Arcs','Japan','http://www.7arcs.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Shaft, Inc. | Shaft','Japan','http://www.shaft-web.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Studio 4°C','Japan','http://www.studio4c.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Studio Comet','Japan','http://www.st-comet.com/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Studio Deen','Japan','http://www.deen.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin) VALUES ('Studio Donguri','Japan');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin) VALUES ('Studio Dub','Japan');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin) VALUES ('Studio Egg','Japan');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Studio Fantasia','Japan','http://www.studiofantasia.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Studio Ghibli','Japan','http://www.ghibli.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Studio Hibari','Japan','http://www.st-hibari.co.jp/en/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin) VALUES ('Studio Junio','Japan');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin) VALUES ('Studio Nue','Japan');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Studio Orphee','Japan','http://homepage2.nifty.com/orphee/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin) VALUES ('Studio Wombat','Japan');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Sunrise Inc. | Sunrise','Japan','http://www.sunrise-inc.co.jp/international/index.html');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('SynergySP','Japan','http://www.synergy-sp.com/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Tatsunoko Production','Japan','http://tatsunoko.co.jp/english');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Telecom Animation Film','Japan','http://www.telecom-anime.com/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Tezuka Productions','Japan','http://tezukaosamu.net/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('TMS Entertainment','Japan','http://www.tms-e.co.jp/english/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('TNK Co., Ltd. | TNK','Japan','http://www.e-tnk.net/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Toei Animation','Japan','http://www.toei-anim.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin) VALUES ('Topcraft','Japan');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Triangle Staff','Japan','https://web.archive.org/web/20000817021414/http://www.t-staff.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Trigger Inc. | Trigger','Japan','http://www.st-trigger.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Ufotable','Japan','http://www.ufotable.com/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('White Fox','Japan','http://w-fox.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Wit Studio','Japan','http://witstudio.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Xebec, Inc. | Xebec','Japan','http://www.xebec-inc.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Yumeta Company','Japan','http://www.yumeta.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Zexcs','Japan','http://www.zexcs.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Phoenix Entertainment','Japan','http://www.phoenix-ent.co.jp/');
INSERT INTO ProductionStudios  (ProductionStudioName,CountryOfOrigin,WebsiteURL) VALUES ('Ashi Productions','Japan','http://ashipro.jp/index.html');



ROLLBACK;


COMMIT;